Add apply page
Fan2Shrek/BourseAuStage-front pull request #33
Opened 2024-05-25 13:50 UTC by Fan2Shrek

2024-05-25 21:39 UTC, BatMaxou requested changes

2024-05-25 21:39 UTC, BatMaxou commented on src/components/layout/Navbar/index.js
> +    offers: '/offres/',
créer la path directement (pareil pour company)

2024-05-25 21:39 UTC, BatMaxou commented on src/components/ui/atoms/Select/index.js
> +            {placeholder && <option value="" disabled selected>{placeholder}</option>}
déjà fait, remet comme avant et rebase

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/apply.module.scss
> +            width: 1200px;
met un max-width sinon le responsive va être compliqué

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/apply.module.scss
> +        }
vraiment pas fan de ce css mais vsy flem t'as mis ca partout

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/apply.module.scss
> +            }
wow ok...

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/index.js
> +            {/* Breadcrumbs */}
Banner et breadcrumb a implementer

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/index.js
> +            </Card>
ici on devrait mettre une OfferCard

2024-05-25 21:39 UTC, BatMaxou commented on src/path.js
> +    'apply': '/offres/postuler/:id',
pas mieux d'avoir /offres/:id/postuler ?

2024-05-25 21:39 UTC, BatMaxou commented on src/translations/i18n.js
> +        },
tu utilises pas de balises dans les trad je crois, donc ca sert a rien

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/index.js
> +
tu veux pas separé en composant un peu
prsq la wow on a bcp de ligne c'est pas facile a comprendre

genre tu crées un folder dans composant que s'appelle Apply et tu mets des composants dedans

2024-05-25 21:39 UTC, BatMaxou commented on src/pages/Offers/Apply/index.js
> +                            <Button className={styles.offerType} label={offer.type} inverted />
c'est un tag

2024-05-25 21:46 UTC, Fan2Shrek commented on src/translations/i18n.js
> +        },
si (les dates)

2024-05-25 21:49 UTC, BatMaxou requested changes

2024-05-25 21:49 UTC, BatMaxou commented on src/pages/Offers/Apply/index.js
> +                    {skills.map((skill) => <Button className={styles.btn} key={skill} label={skill} />)}
il manque l'icon de croix (pareil pour les autres en dessous dcp)

2024-05-26 07:28 UTC, BatMaxou requested changes

2024-05-26 07:28 UTC, BatMaxou commented on src/components/ui/atoms/Input/index.js
> +            value={value}
pareil ces changement sont dans la PR de l'input type file

2024-05-26 07:31 UTC, BatMaxou requested changes

2024-05-26 07:31 UTC, BatMaxou commented on src/components/ui/atoms/Select/index.js
> +            {placeholder && <option value="" disabled selected>{placeholder}</option>}
t'as pas remis  comme avant ?

2024-05-26 07:32 UTC, BatMaxou submitted a review, later dismissed

2024-05-26 07:32 UTC, BatMaxou commented on src/pages/Offers/Apply/apply.module.scss
> +            width: 1200px;
t'as pas mis le max-width

2024-05-26 07:33 UTC, Fan2Shrek commented on src/pages/Offers/Apply/apply.module.scss
> +            width: 1200px;
ca casse tout

2024-06-02 21:00 UTC, BatMaxou approved these changes

2024-06-02 21:00 UTC, merged